# Generated by Django 4.1 on 2022-09-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_post_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='user',
        ),
    ]
