# Generated by Django 4.1 on 2022-09-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
